# Generated by Django 5.2.3 on 2025-06-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('doses', models.PositiveIntegerField(default=1, verbose_name='Número de doses')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Fornecedor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='type.type', verbose_name='Tipo')),
            ],
            options={
                'db_table': 'CORE_VACCINE',
            },
        ),
    ]
