# Generated by Django 5.2.3 on 2025-06-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrationroute', '0001_initial'),
        ('clinic', '0001_initial'),
        ('person', '0001_initial'),
        ('professional', '0001_initial'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Data do Atendimento')),
                ('administration_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrationroute.administrationroute', verbose_name='Via de administração')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic', verbose_name='Clínica')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.person', verbose_name='Paciente')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='professional.professional', verbose_name='Profissional')),
                ('vaccines', models.ManyToManyField(blank=True, to='vaccine.vaccine', verbose_name='Vacinas')),
            ],
            options={
                'db_table': 'CORE_SESSION',
            },
        ),
    ]
