# Generated by Django 5.2 on 2025-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('dose', models.IntegerField(verbose_name='Número da Dose')),
                ('data_aplicacao', models.DateField(verbose_name='Data de Aplicação')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['nome'],
            },
        ),
    ]
