# Generated by Django 5.2.3 on 2025-06-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=50, verbose_name='Função')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
            ],
            options={
                'db_table': 'CORE_PROFESSIONAL',
            },
        ),
    ]
